version: '3'

services:
  e_edu_bot:
    image: eedu/discord-bot
    environment:
      - DISCORD_TOKEN= # Need to be replaced with token
    volumes:
      - /var/data/config/:/Discord/config
    restart: unless-stopped
    container_name: e_edu_bot
